plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - inbox.md
  - pull_request_template.md
  - README.md
  - LICENSE

theme: jekyll-theme-cayman
